#6Fixed CowBreed Model and Validation Strategy
AgriCodeHub/dairy-django-backend pull request #8
Opened 2023-12-19 00:02 UTC by mamesareagan

This pull request addresses several issues and improvements related to the CowBreed model and its validation strategy. Here's a summary of the changes:

**Model Fix:**

Corrected the BreedChoices enum to match the choices provided in the CowBreed model.
Resolved the AttributeError issue when trying to create a breed with an invalid name.
**Validation Strategy:**

Updated the CustomCowBreedValidator to use the correct ValidationError import from Django.
Adjusted the validation logic to ensure the breed name is within the specified choices and is not an empty string.
**Tests:**

Added new tests to cover various scenarios, including creating breeds with valid and invalid names, as well as empty names.
Fixed existing tests to align with the corrected model and validation strategy.

2023-12-19 08:49 UTC, peter-evance requested changes

2023-12-19 08:49 UTC, peter-evance commented on dairy/settings.py
> +# Add the custom validator for CowBreed model
Unnecessary implementation, this file (settings.py) is solely for global settings for our whole application, model related stuff should be in the respective app folder

2023-12-19 08:49 UTC, peter-evance commented on tests/users/tests/test_models.py
> +class TestCowBreedModel:
Test case should be moved into another app test folder, this is for users app and it's related test logic

2023-12-19 08:49 UTC, peter-evance commented on users/models.py
> +class CowBreed(models.Model):
Model should be moved to the core app, not users.models.py

2023-12-19 08:49 UTC, peter-evance commented on users/urls.py
> +# Add a new router for CowBreed
Clean up the code, remove unnecessary comments

2023-12-19 08:49 UTC, peter-evance commented on users/validators.py
> +class CustomCowBreedValidator:
Should be moved to a much appropriate app location—core app

2023-12-19 16:48 UTC, mamesareagan commented on users/models.py
> +class CowBreed(models.Model):
What does this mean,I quite didn't get it clearly

2023-12-19 16:54 UTC, peter-evance commented on users/models.py
> +class CowBreed(models.Model):
> What does this mean,I quite didn't get it clearly

Models such as cow breed , cow, milk etc are the core of our application thus they should be in the `core` app , users app is/must only have code related to users management and roles to separate concerns and make the code base easy to understand

2023-12-20 12:39 UTC, mamesareagan reviewed
I have checked the issues raised and they are all fixed as expected.

2023-12-20 13:26 UTC, closed without merging